# Generated by Django 3.2.25 on 2025-01-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
